version: '3'

services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    links:
      - postgres:postgres
    volumes:
      - web-data:/usr/src/app/static
    env_file: 
      - .env
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - .:/www/static
      - web-data:/usr/src/app/static
    links:
      - web:web

  data:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    command: "true"

  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "hdma"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - ./postgres/csvs:/var/lib/postgresql/csvs
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    # command:
    #   - "postgres"
    #   - "-c"
    #   - "max_wal_size=1GB"
  
volumes:
  db-data:
  web-data:
