CREATE TABLE public.hdma
(
    "id"                                        SERIAL PRIMARY KEY,
    "activity_year"                             CHARACTER VARYING (200) NOT NULL, 
    "lei"                                       CHARACTER VARYING (200) NOT NULL,
    "derived_msa-md"                            CHARACTER VARYING (200) NOT NULL, 
    "state_code"                                CHARACTER VARYING (200) NOT NULL, 
    "county_code"                               CHARACTER VARYING (200), 
    "census_tract"                              CHARACTER VARYING (200),
    "conforming_loan_limit"                     CHARACTER VARYING (200), 
    "derived_loan_product_type"                 CHARACTER VARYING (200), 
    "derived_dwelling_category"                 CHARACTER VARYING (200), 
    "derived_ethnicity"                         CHARACTER VARYING (200), 
    "derived_race"                              CHARACTER VARYING (200), 
    "derived_sex"                               CHARACTER VARYING (200),
    "action_taken"                              CHARACTER VARYING (200), 
    "purchaser_type"                            CHARACTER VARYING (200), 
    "preapproval"                               CHARACTER VARYING (200), 
    "loan_type"                                 CHARACTER VARYING (200), 
    "loan_purpose"                              CHARACTER VARYING (200),
    "lien_status"                               CHARACTER VARYING (200), 
    "reverse_mortgage"                          CHARACTER VARYING (200), 
    "open-end_line_of_credit"                   CHARACTER VARYING (200), 
    "business_or_commercial_purpose"            CHARACTER VARYING (200), 
    "loan_amount"                               CHARACTER VARYING (200),
    "loan_to_value_ratio"                       CHARACTER VARYING (200),
    "interest_rate"                             CHARACTER VARYING (200), 
    "rate_spread"                               CHARACTER VARYING (200), 
    "hoepa_status"                              CHARACTER VARYING (200), 
    "total_loan_costs"                          CHARACTER VARYING (200),
    "total_points_and_fees"                     CHARACTER VARYING (200), 
    "origination_charges"                       CHARACTER VARYING (200), 
    "discount_points"                           CHARACTER VARYING (200), 
    "lender_credits"                            CHARACTER VARYING (200), 
    "loan_term"                                 CHARACTER VARYING (200), 
    "prepayment_penalty_term"                   CHARACTER VARYING (200), 
    "intro_rate_period"                         CHARACTER VARYING (200), 
    "negative_amortization"                     CHARACTER VARYING (200),
    "interest_only_payment"                     CHARACTER VARYING (200),
    "balloon_payment"                           CHARACTER VARYING (200), 
    "other_nonamortizing_features"              CHARACTER VARYING (200), 
    "property_value"                            CHARACTER VARYING (200), 
    "construction_method"                       CHARACTER VARYING (200), 
    "occupancy_type"                            CHARACTER VARYING (200), 
    "manufactured_home_secured_property_type"   CHARACTER VARYING (200),
    "manufactured_home_land_property_interest"  CHARACTER VARYING (200),
    "total_units"                               CHARACTER VARYING (200), 
    "multifamily_affordable_units"              CHARACTER VARYING (200),
    "income"                                    CHARACTER VARYING (200),
    "debt_to_income_ratio"                      CHARACTER VARYING (200), 
    "applicant_credit_score_type"               CHARACTER VARYING (200), 
    "co-applicant_credit_score_type"            CHARACTER VARYING (200), 
    "applicant_ethnicity-1"                     CHARACTER VARYING (200),
    "applicant_ethnicity-2"                     CHARACTER VARYING (200),
    "applicant_ethnicity-3"                     CHARACTER VARYING (200),
    "applicant_ethnicity-4"                     CHARACTER VARYING (200), 
    "applicant_ethnicity-5"                     CHARACTER VARYING (200), 
    "co-applicant_ethnicity-1"                  CHARACTER VARYING (200), 
    "co-applicant_ethnicity-2"                  CHARACTER VARYING (200),
    "co-applicant_ethnicity-3"                  CHARACTER VARYING (200),
    "co-applicant_ethnicity-4"                  CHARACTER VARYING (200), 
    "co-applicant_ethnicity-5"                  CHARACTER VARYING (200), 
    "applicant_ethnicity_observed"              CHARACTER VARYING (200),
    "co-applicant_ethnicity_observed"           CHARACTER VARYING (200), 
    "applicant_race-1"                          CHARACTER VARYING (200), 
    "applicant_race-2"                          CHARACTER VARYING (200), 
    "applicant_race-3"                          CHARACTER VARYING (200), 
    "applicant_race-4"                          CHARACTER VARYING (200), 
    "applicant_race-5"                          CHARACTER VARYING (200), 
    "co-applicant_race-1"                       CHARACTER VARYING (200),
    "co-applicant_race-2"                       CHARACTER VARYING (200), 
    "co-applicant_race-3"                       CHARACTER VARYING (200), 
    "co-applicant_race-4"                       CHARACTER VARYING (200), 
    "co-applicant_race-5"                       CHARACTER VARYING (200), 
    "applicant_race_observed"                   CHARACTER VARYING (200), 
    "co-applicant_race_observed"                CHARACTER VARYING (200), 
    "applicant_sex"                             CHARACTER VARYING (200), 
    "co-applicant_sex"                          CHARACTER VARYING (200), 
    "applicant_sex_observed"                    CHARACTER VARYING (200), 
    "co-applicant_sex_observed"                 CHARACTER VARYING (200),
    "applicant_age"                             CHARACTER VARYING (200),
    "co-applicant_age"                          CHARACTER VARYING (200), 
    "applicant_age_above_62"                    CHARACTER VARYING (200), 
    "co-applicant_age_above_62"                 CHARACTER VARYING (200), 
    "submission_of_application"                 CHARACTER VARYING (200), 
    "initially_payable_to_institution"          CHARACTER VARYING (200),
    "aus-1"                                     CHARACTER VARYING (200), 
    "aus-2"                                     CHARACTER VARYING (200), 
    "aus-3"                                     CHARACTER VARYING (200), 
    "aus-4"                                     CHARACTER VARYING (200),
    "aus-5"                                     CHARACTER VARYING (200), 
    "denial_reason-1"                           CHARACTER VARYING (200),
    "denial_reason-2"                           CHARACTER VARYING (200), 
    "denial_reason-3"                           CHARACTER VARYING (200), 
    "denial_reason-4"                           CHARACTER VARYING (200), 
    "tract_population"                          CHARACTER VARYING (200), 
    "tract_minority_population_percent"         CHARACTER VARYING (200),
    "ffiec_msa_md_median_family_income"         CHARACTER VARYING (200),
    "tract_to_msa_income_percentage"            CHARACTER VARYING (200),
    "tract_owner_occupied_units"                CHARACTER VARYING (200), 
    "tract_one_to_four_family_homes"            CHARACTER VARYING (200),
    "tract_median_age_of_housing_units"         CHARACTER VARYING (200)
);

COPY hdma (
    "activity_year",
    "lei",
    "derived_msa-md",
    "state_code",
    "county_code",
    "census_tract",
    "conforming_loan_limit",
    "derived_loan_product_type",
    "derived_dwelling_category",
    "derived_ethnicity",
    "derived_race",
    "derived_sex",
    "action_taken",
    "purchaser_type",
    "preapproval",
    "loan_type",
    "loan_purpose",
    "lien_status",
    "reverse_mortgage",
    "open-end_line_of_credit",
    "business_or_commercial_purpose",
    "loan_amount",
    "loan_to_value_ratio",
    "interest_rate",
    "rate_spread",
    "hoepa_status",
    "total_loan_costs",
    "total_points_and_fees",
    "origination_charges",
    "discount_points",
    "lender_credits",
    "loan_term",
    "prepayment_penalty_term",
    "intro_rate_period",
    "negative_amortization",
    "interest_only_payment",
    "balloon_payment",
    "other_nonamortizing_features",
    "property_value",
    "construction_method",
    "occupancy_type",
    "manufactured_home_secured_property_type",
    "manufactured_home_land_property_interest",
    "total_units",
    "multifamily_affordable_units",
    "income",
    "debt_to_income_ratio",
    "applicant_credit_score_type",
    "co-applicant_credit_score_type",
    "applicant_ethnicity-1",
    "applicant_ethnicity-2",
    "applicant_ethnicity-3",
    "applicant_ethnicity-4",
    "applicant_ethnicity-5",
    "co-applicant_ethnicity-1",
    "co-applicant_ethnicity-2",
    "co-applicant_ethnicity-3",
    "co-applicant_ethnicity-4",
    "co-applicant_ethnicity-5",
    "applicant_ethnicity_observed",
    "co-applicant_ethnicity_observed",
    "applicant_race-1",
    "applicant_race-2",
    "applicant_race-3",
    "applicant_race-4",
    "applicant_race-5",
    "co-applicant_race-1",
    "co-applicant_race-2",
    "co-applicant_race-3",
    "co-applicant_race-4",
    "co-applicant_race-5",
    "applicant_race_observed",
    "co-applicant_race_observed",
    "applicant_sex",
    "co-applicant_sex",
    "applicant_sex_observed",
    "co-applicant_sex_observed",
    "applicant_age",
    "co-applicant_age",
    "applicant_age_above_62",
    "co-applicant_age_above_62",
    "submission_of_application",
    "initially_payable_to_institution",
    "aus-1",
    "aus-2",
    "aus-3",
    "aus-4",
    "aus-5",
    "denial_reason-1",
    "denial_reason-2",
    "denial_reason-3",
    "denial_reason-4",
    "tract_population",
    "tract_minority_population_percent",
    "ffiec_msa_md_median_family_income",
    "tract_to_msa_income_percentage",
    "tract_owner_occupied_units",
    "tract_one_to_four_family_homes",
    "tract_median_age_of_housing_units"
) FROM '/var/lib/postgresql/csvs/state_IL.csv' DELIMITER ',' CSV HEADER;

